MAAP-Project/maap-workspaces

jupyterlab3/docker/Dockerfile

Updated conda-forge install command for ipyleaflet

Fixed conda-forge install command for ipyleaflet

---

base_images/isce2/docker/Dockerfile

Updated isce2 image with latest miniconda and isce2 conda package.

---

base_images/isce2/docker/Dockerfile

Plant installs jupyter, so had to disable a conflicting server extension

Added Plant as part of the isce2 workspace

---

devfiles/pangeo/devfile/meta.yaml

Replaced generic description text for Pangeo workspace with its version number for clarity.

Updated description for Pangeo workspace to include the version number.

---

devfiles/isce2/devfile/meta.yaml

Updated Title, Description and Tags for ISCE2 devfile.

Updated ISCE2 description to include "PLAnT"

---

jupyterlab3/docker/Dockerfile

new version contains updates to support new DPSJob object

updated jupyter-server-ext version

---

jupyterlab3/docker/Dockerfile

This version of the dps jupyter extension contains styling fixes, a fix to a bug when trying to display data from a queued job, and a spinner while the user waits for job submission to complete.

bumped dps jupyter ext

---

jupyterlab3/pangeo/environment.yml

We missed a currently required ENV variable.

Add STAC_BROWSER_URL env var

---

Makefile
jupyterlab3/shared/environment.yml

Added `stac_ipyleaflet` to the shared environment yml which supports the vanilla, isce3 and r workspaces.

Add `stac_ipyleaflet`

---

devfiles/edav/devfile/devfile.yaml
devfiles/isce2/devfile/devfile.yaml
devfiles/isce3/devfile/devfile.yaml
devfiles/pangeo/devfile/devfile.yaml
devfiles/r/devfile/devfile.yaml
devfiles/rgedi/devfile/devfile.yaml
devfiles/vanilla/devfile/devfile.yaml
jupyterlab3/environments.json

Update all devfiles with the correct s3fs sidecar image urls.

Fix s3fs sidecar image urls

---

base_images/isce3/docker/Dockerfile
base_images/pangeo/docker/Dockerfile
base_images/r/docker/Dockerfile
base_images/vanilla/docker/Dockerfile

Upgrade maap-py version to v3.1.5 pre-release 
I believe this is the final thing I have to do before we can start testing in DIT

upgrade maap-py to v3.1.5

---

devfiles/isce3/devfile/meta.yaml
devfiles/pangeo/devfile/meta.yaml
devfiles/python/devfile/meta.yaml
devfiles/r/devfile/meta.yaml

Captured In this PR is the removal of version information from the description field in each of our primary workspace's `meta.yaml` file.

Update workspace yaml

---

devfiles/python/devfile/devfile.yaml

Update the python devfile base image from **vanilla** to **python**

Update Python devfile.yaml DOCKERIMAGE_PATH env

---

jupyterlab/pangeo/environment.yml

Removes package
Test with: 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab/pangeo:remove-package'

Remove package

---

base_images/isce3/environment.yml
base_images/pangeo/environment.yml
base_images/python/environment.yml
base_images/r/environment.yml

Upgraded to maap-py v4.1.0. Major updates in this version include:
- user secrets management
- filtering on queries for the listJobs endpoint
- maap-py CI/CD
See maap-py v4.1.0 details [here](https://github.com/MAAP-Project/maap-py/releases/tag/v4.1.0).

upgraded to maap-py v4.1.0

---

jupyterlab/pangeo/environment.yml

upgraded extensions in pangeo jupyterlab/environment.yml

Feature/upgrade pangeo extensions (#145)

---

base_images/r/docker/Dockerfile

This package is annoying and starts just randomly erroring out every once in a while unless you update it.
Currently the R image in the develop branch is failing which is why this change needs to be made 
Successful update build: https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/15928 
Had to do this before here: https://github.com/MAAP-Project/maap-workspaces/pull/143/files

Libpq dev update

---

base_images/isce3/docker/Dockerfile
base_images/pangeo/docker/Dockerfile
base_images/python/docker/Dockerfile
base_images/r/docker/Dockerfile

Successful builds: https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/8812 
Sujen agreed this is the best way on slack, so I am just going to merge without approval

Maap base develop

---

base_images/r/docker/Dockerfile

Updated to lasR 0.13.7 by request of Sam Grubinger

lasR 0.13.7

---

base_images/r/docker/Dockerfile

Update libpq dev so that develop can build

Update libpq dev
