- jupyterlab3/docker/Dockerfile
I've added ipyleaflet to the list of jupyter extensions that are installed to see if this will allow ipyleaflet to be used in notebooks.
The associated ticket for this task is here: https://github.com/MAAP-Project/ZenHub/issues/668
> Added ipyleaflet to the list of jupyter extensions installed via mamba.

- jupyterlab3/docker/Dockerfile
This PR introduces an additional installation that is needed for ipyleaflet to function since we are running JupyterLab 2.1.4 in UAT.
> Add ipyleaflet support

- jupyterlab3/docker/Dockerfile
This PR includes one change to the jupyterlab3 Dockerfile in which `ipyleaflet` is now being installed.
> Added ipyleaflet installation to jupyterlab3 Dockerfile.

- jupyterlab3/docker/Dockerfile
Added an innocuous change to retrigger the build pipeline to test the addition of ipyleaflet to our Jupyter workspaces. The prior image build didn't work because we recently changed the names of our branches.
> Added a change to trigger a build of our workspaces due to branch renames.

- devfiles/edav/devfile/devfile.yaml
- devfiles/isce2/devfile/devfile.yaml
- devfiles/pangeo/devfile/devfile.yaml
- devfiles/r/devfile/devfile.yaml
- devfiles/rgedi/devfile/devfile.yaml
- devfiles/vanilla/devfile/devfile.yaml
Updated all our workspace devfiles.yaml files to address the renaming of our "dit" branch to "develop".  This PR addresses the resolution for issue [#682](https://github.com/MAAP-Project/ZenHub/issues/682)
Brian and I came to the conclusion that ADE is referencing images that are tagged with "dit" instead of "develop", thereby not allowing us to test updates to our workspaces.
> `devfile.yaml` updates to reference 'develop' branch

- devfiles/pangeo/devfile/meta.yaml
Added missing comma in tag list for pangeo `meta.yaml` file.
> fix pangeo meta yaml

- jupyterlab3-build/docker/Dockerfile
George recommended removing the pinned versions of nodejs and jupyter-packaging to determine if these are causing the issues we are experiencing when building the pangeo workspace.
If the test fails, we'll revert this change.
> Updated pangeo base image

- jupyterlab3/docker/Dockerfile
Incremented nodejs version by one revision to 16.14.2 to resolve a dependency issue with the isce2 base build. Tested locally and build still goes to completion with this newer version.
> Update Node JS to solve dependency issue with ISCE2

- base_images/isce2/docker/Dockerfile
Upon testing the workspace, it turns out that maap-py.cfg is nowhere to be found! Restructuring build to look more like vanilla in hopes that it'll probably keep the /maap-py folder.
> Moving maap-py install to match vanilla

- jupyterlab3/pangeo/environment.yml
This PR addresses the addition of [stac_ipyleaflet](https://github.com/MAAP-Project/stac_ipyleaflet), version [0.2.0](https://github.com/MAAP-Project/stac_ipyleaflet/releases/tag/0.2.0), to our Pangeo workspace. It also includes the addition of packages that were missing as reported by @wildintellect .
> Add `stac_ipyleaflet` to Pangeo workspace

- jupyterlab3/docker/Dockerfile
Updating maap libs jupyter extension, which had the following changes:
Changed from INotifications to Notification from the @jupyterlab/apputil package
Also, changed maapsec/environment to jupyter-server-extension/getConfig so now using the MAAP icon works correctly adding the api_server when creating a MAAP instance
ie
```
from maap.maap import MAAP
maap = MAAP(maap_host='api.dit.maap-project.org')
```
Created a vanilla image to test here: 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:jlab-notifs-maap-libs'
> updated version of maap libs jupyter extension

- jupyterlab3/docker/Dockerfile
- jupyterlab3/entrypoint.sh
Added a memory extension which tells the user how much memory they are currently using for a workspace out of how much available energy. The icon will turn red if they only have 20% of memory left. The maximum memory allocation is found in the entrypoint.sh (extracted from what the user put in the devfile)
Build for all base images here: https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/3224, vanilla successful in this one with same code: https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/3231
Rgedi failing is unrelated
Tried building workspaces in DIT for all images but rgedi, and all contain the memory extension
Completes: https://github.com/MAAP-Project/Community/issues/749
> Added memory extension

- base_images/isce3/environment.yml
- base_images/pangeo/environment.yml
- base_images/r/environment.yml
- base_images/vanilla/environment.yml
- jupyterlab3/docker/Dockerfile
Added `groff` to all base_image environment.ymls so that awscli was fixed (used `aws s3 help` as the indicator) 
Tested for vanilla, r, pangeo, and isce3
Test images: 
mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:awscli
mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/r:awscli
mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/pangeo:awscli
mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/isce3:awscli
> Awscli bug

- jupyterlab3/docker/Dockerfile
- updated package installation to use pip install 
- umf extension has been removed since the CMR metadata form is no longer used and there is no equivalent to take its place
> changed to use pip install

- devfiles/isce3/devfile/meta.yaml
- devfiles/pangeo/devfile/meta.yaml
- devfiles/r/devfile/meta.yaml
- devfiles/vanilla/devfile/meta.yaml
@wildintellect noted that the devfile description for Pangeo appearing in the Get Started tab of the ADE contained an outdated version. This PR updates all the devfiles to include the correct version number to match the convention used in OPS.
> Update devfile metadata

- devfiles/isce3/devfile/devfile.yaml
- devfiles/pangeo/devfile/devfile.yaml
- devfiles/r/devfile/devfile.yaml
- devfiles/vanilla/devfile/devfile.yaml
Define the `DOCKERIMAGE_PATH` environment variable within all JupyterLab workspace devfiles to provide the correct base image path when registering algorithms.
See: https://github.com/MAAP-Project/Community/issues/869
> Add devfile docker path env vars

- jupyterlab/shared/environment.yml
Both of these links open in a new tab
> Algorithm registration links now open in a new tab

- jupyterlab/shared/environment.yml
We've moved the `/stac` endpoint from the titiler-stac tiler to the titiler-pgstac tiler and plan on tearing down titiler-stac to address a MCP security issue
> chore: update titiler-stac

- jupyterlab/shared/environment.yml
Newer version addresses issue with the low number of jobs shown in the jobs ui. 
Image with this newer version:
mas.dit.maap-project.org/root/maap-workspaces/jupyterlab/python:bump-jupyter-server-ext
> Bumped jupyter-server-ext version

- base_images/isce3/environment.yml
- base_images/pangeo/environment.yml
- base_images/python/environment.yml
- base_images/r/environment.yml
- devfiles/isce3/devfile/meta.yaml
- devfiles/pangeo/devfile/meta.yaml
- devfiles/python/devfile/meta.yaml
- devfiles/r/devfile/meta.yaml
- jupyterlab/pangeo/environment.yml
- jupyterlab/shared/environment.yml
Includes:
- removing `pygeos` from all base images
- upgrade to jupyter server extension which sets page size back to 200 so user can see 200 most recent jobs in pages
> Develop into main for 4.1.1 release 

- base_images/isce3/environment.yml
- base_images/pangeo/environment.yml
- base_images/python/environment.yml
- base_images/r/environment.yml
Maap-py pointing back to develop because builds fail otherwise since other tag doesn't exist
> maap-py pointing back to develop
